site_name: Serverless Python
site_url: https://chrisfx.github.io/serverless-python/

nav:
  - Inicio: 
      - Introducción: index.md
      - Python + Serveless: python-serverless.md
      - Diagrama: diagramaPythonServerless.md
  - Fundamentos:
      - ¿Qué es Serverless?: serverless.md
      - Casos de uso Python y Serverless: casosdeuso.md
  - Herramientas Python Serverless:
      - AWS Chalice: chalice.md
      - Serverless Framework: serverless-framework.md
      - AWS SAM: aws-sam.md
      - Comparativa: comparativa.md
  - Tecnologías Clave:
      - Servicios en acción: tecnologias.md
      - Mini-demo: mini-demo.md
  - Cierre:
      - Recapitulación y recursos: referencias.md
theme:
  name: material


plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - js/init-mermaid.js