site_name: Serverless Python
site_url: https://chrisfx.github.io/serverless-python/

nav:
  - Inicio:
      - Introducción: index.md
      - Python + Serverless: python-serverless.md
      - Diagrama general: diagramaPythonServerless.md # Mejorarlo

  - Fundamentos Serverless:
      - ¿Qué es Serverless?: serverless.md
      - Casos de uso con Python: casosdeuso.md
      - Servicios clave en AWS: tecnologias.md

  - Preparación del entorno:
      - Requisitos y recomendaciones: recomendaciones-apis.md
      - Instalación de entorno virtual (uv): instalacion-uv.md
      - Configuración de cuenta AWS: aws-setup.md
      - Verificación del entorno: verificacion-entorno.md  # (opcional pero útil)

  - Frameworks Serverless con Python:
      - AWS Chalice:
          - Instalación y configuración: chalice.md
      - Serverless Framework:
          - Instalación y configuración: serverless-framework.md
      - AWS SAM:
          - Instalación: aws-sam-instalacion.md
          - Uso básico: aws-sam.md
      - Comparativa de frameworks: comparativa.md

  - Buenas prácticas:
      - Buenas prácticas y seguridad: buenas-practicas.md

  - Recursos y referencias:
      - Referencias: referencias.md # Agregar bibliografía 
      - Enlaces útiles: enlaces.md
      - Glosario de términos: glosario.md

theme:
  name: material


plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - js/init-mermaid.js

extra_css:
  - css/extra.css 