site_name: Serverless Python
site_url: https://chrisfx.github.io/serverless-python/

nav:
  - Home: index.md
  - Workshop Guide:
      - Step 1: intro.md
      - Step 2: setup.md
      - Step 3: deploy.md
theme:
  name: material